# Generated by Django 5.2 on 2026-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='crs',
            field=models.CharField(default='EPSG:4326', max_length=32),
        ),
        migrations.AddField(
            model_name='layer',
            name='original_crs',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
